-- CREATE DATABASE IF NOT EXISTS
CREATE DATABASE IF NOT EXISTS pluto;

-- SELECT DATABASE
USE pluto;

-- CREATE TABLE IF NOT EXISTS
CREATE TABLE IF NOT EXISTS posts (
    id VARCHAR(36),
    stamp VARCHAR(20)
);